const OMR_HEADER_HEIGHT = 38;
const OMR_ROW_HEIGHT = 55;
const OMR_BODY_ROW_COUNT = 10;
const OMR_BODY_DASHED_DIVIDER_HEIGHT = 1;
const OMR_BODY_BORDER_COMPENSATION = 1.5;

const OMR_INFO_TABLE_WIDTH = 200;
const OMR_INFO_LABEL_COLUMN_WIDTH = 30;
const OMR_OBJECTIVE_SECTION_WIDTH = 552;
const OMR_SUBJECTIVE_SECTION_WIDTH = 360;
const OMR_NUMERIC_KEYPAD_WIDTH = 243;
const OMR_BRANDING_LOGO_SIZE = 72;

const OMR_LABEL_WIDTH = 28;
const OMR_BUBBLE_WIDTH = 20;
const OMR_READER_MARK_WIDTH = 8;

const OMR_OBJECTIVE_COLUMN_COUNT = 3;
const OMR_OBJECTIVE_COLUMN_WIDTH = OMR_OBJECTIVE_SECTION_WIDTH / OMR_OBJECTIVE_COLUMN_COUNT;
const OMR_OBJECTIVE_CHOICE_COUNT = 5;
const OMR_OBJECTIVE_BUBBLE_GAP = 10;
const OMR_OBJECTIVE_TRACK_PADDING_X = 6;

const OMR_NUMBER_DIGIT_COUNT = 2;
const OMR_NUMBER_TRACK_GAP = 6;
const OMR_GRADE_COLUMN_SIDE_PADDING_X = 8;
const OMR_NUMBER_COLUMN_SIDE_PADDING_X = 10;

const OMR_BODY_HEIGHT =
  OMR_ROW_HEIGHT * OMR_BODY_ROW_COUNT +
  OMR_BODY_DASHED_DIVIDER_HEIGHT +
  OMR_BODY_BORDER_COMPENSATION;

const OMR_OBJECTIVE_TRACK_WIDTH =
  OMR_BUBBLE_WIDTH * OMR_OBJECTIVE_CHOICE_COUNT +
  OMR_OBJECTIVE_BUBBLE_GAP * (OMR_OBJECTIVE_CHOICE_COUNT - 1) +
  OMR_OBJECTIVE_TRACK_PADDING_X * 2;

const OMR_NUMBER_TRACK_WIDTH =
  OMR_BUBBLE_WIDTH * OMR_NUMBER_DIGIT_COUNT + OMR_NUMBER_TRACK_GAP * (OMR_NUMBER_DIGIT_COUNT - 1);

const OMR_GRADE_COLUMN_WIDTH = OMR_BUBBLE_WIDTH + OMR_GRADE_COLUMN_SIDE_PADDING_X * 2;
const OMR_NUMBER_COLUMN_WIDTH = OMR_NUMBER_TRACK_WIDTH + OMR_NUMBER_COLUMN_SIDE_PADDING_X * 2;
const OMR_DEFAULT_SUBJECTIVE_INPUT_WIDTH = 322;

export const OMR_STYLES = {
  HEADER_HEIGHT: OMR_HEADER_HEIGHT,
  ROW_HEIGHT: OMR_ROW_HEIGHT,
  BODY_ROW_COUNT: OMR_BODY_ROW_COUNT,
  BODY_DASHED_DIVIDER_HEIGHT: OMR_BODY_DASHED_DIVIDER_HEIGHT,
  BODY_BORDER_COMPENSATION: OMR_BODY_BORDER_COMPENSATION,
  BODY_HEIGHT: OMR_BODY_HEIGHT,
  READER_HEIGHT: 36,
  INFO_TABLE_WIDTH: OMR_INFO_TABLE_WIDTH,
  INFO_LABEL_COLUMN_WIDTH: OMR_INFO_LABEL_COLUMN_WIDTH,
  OBJECTIVE_COLUMN_COUNT: OMR_OBJECTIVE_COLUMN_COUNT,
  OBJECTIVE_COLUMN_WIDTH: OMR_OBJECTIVE_COLUMN_WIDTH,
  OBJECTIVE_SECTION_WIDTH: OMR_OBJECTIVE_SECTION_WIDTH,
  SUBJECTIVE_SECTION_WIDTH: OMR_SUBJECTIVE_SECTION_WIDTH,
  NUMERIC_KEYPAD_WIDTH: OMR_NUMERIC_KEYPAD_WIDTH,
  BRANDING_LOGO_SIZE: OMR_BRANDING_LOGO_SIZE,
  LABEL_WIDTH: OMR_LABEL_WIDTH,
  BUBBLE_WIDTH: OMR_BUBBLE_WIDTH,
  OBJECTIVE_CHOICE_COUNT: OMR_OBJECTIVE_CHOICE_COUNT,
  OBJECTIVE_BUBBLE_GAP: OMR_OBJECTIVE_BUBBLE_GAP,
  OBJECTIVE_TRACK_PADDING_X: OMR_OBJECTIVE_TRACK_PADDING_X,
  OBJECTIVE_TRACK_WIDTH: OMR_OBJECTIVE_TRACK_WIDTH,
  READER_MARK_WIDTH: OMR_READER_MARK_WIDTH,
  NUMBER_DIGIT_COUNT: OMR_NUMBER_DIGIT_COUNT,
  NUMBER_TRACK_GAP: OMR_NUMBER_TRACK_GAP,
  NUMBER_TRACK_WIDTH: OMR_NUMBER_TRACK_WIDTH,
  GRADE_COLUMN_SIDE_PADDING_X: OMR_GRADE_COLUMN_SIDE_PADDING_X,
  GRADE_COLUMN_WIDTH: OMR_GRADE_COLUMN_WIDTH,
  NUMBER_COLUMN_SIDE_PADDING_X: OMR_NUMBER_COLUMN_SIDE_PADDING_X,
  NUMBER_COLUMN_WIDTH: OMR_NUMBER_COLUMN_WIDTH,
  DEFAULT_SUBJECTIVE_INPUT_WIDTH: OMR_DEFAULT_SUBJECTIVE_INPUT_WIDTH,
};
